### ISSUE TITLE
[2.14.0] P1 Bug: Web wallet error display

### ISSUE THREAD

**Issue by Eshwari007** [leather-io/extension#1597] opened 2021-08-20 14:56 UTC
User was in Mainnet
Upon submitting few transactions and deployed contracts via the sandbox user receive the following error.
Am trying to reload the extension and yet it isnt working.
Deleted the ext and downloaded again from Chrome store .Yet similar issue surfacing
<img width="382" alt="Screen Shot 2021-08-20 at 10 51 05 AM" src="https://user-images.githubusercontent.com/38872890/130252634-ebc08c29-5190-435f-b3e9-104da7bc8038.png">
<img width="1181" alt="Screen Shot 2021-08-20 at 10 54 43 AM" src="https://user-images.githubusercontent.com/38872890/130252635-f2324ffd-665a-4837-a84d-550651819997.png">

**Comment by kyranjamie** [comment] 2021-08-20 14:59
@beguene could this because not all the values are being initalised as `BigNumber` in `mergeAssetBalances`?

**Comment by fbwoolf** [comment] 2021-08-20 15:06
Duplicate of https://github.com/blockstack/stacks-wallet-web/issues/1596

**Comment by beguene** [comment] 2021-08-20 15:12
> @beguene could this because not all the values are being initalised as `BigNumber` in `mergeAssetBalances`?

Yes I think so.

**Closed as completed** 2021-08-20 21:41 UTC
Labels: bug, bug-p1
