### ISSUE TITLE
Can't switch accounts after creating a new one

### ISSUE THREAD

**Issue by jasperjansz** [leather-io/extension#1011] opened 2021-02-19 17:42 UTC
I've created a bunch of new accounts but it doesn't switch to them automatically and it doesn't give me the option to switch from the menu either

![image](https://user-images.githubusercontent.com/25477905/108541031-445c3100-72e2-11eb-9bf7-b6ad9a6f4899.png)

**Comment by andresgalante** [comment] 2021-03-09 19:42
Is it fixed by #1036? Is this one ready for QA?

**Comment by timstackblock** [comment] 2021-03-10 20:40
No this isnt working @andresgalante at some point we actually removed this option.
I cannot find the issue but we had this functionality and removed it it still hasnt been added back.

**Comment by timstackblock** [comment] 2021-03-10 20:57
<img width="400" alt="Screen Shot 2021-03-10 at 3 33 11 PM" src="https://user-images.githubusercontent.com/49165468/110693894-f5553d80-81b5-11eb-9bd5-01995dad87ac.png">

**Comment by hstove** [comment] 2021-03-10 22:44
Hey @timstackblock , this is actually the expected behavior. When you create a new wallet, you only have one account. If you only have one account, you can't switch accounts, you can only create a new account. The root cause of this issue is that when you clicked "create new account", you couldn't then switch to your new accounts. Now, you can successfully "create a new account", and then switch accounts.

Moving back to QA - lmk if you think the "create an account" issue is still present.

**Comment by timstackblock** [comment] 2021-03-11 23:18
I currently cannot switch between my accounts. When I create a new account I get a message that says the account was created successfully but I do not get the option to switch. Please see the video link here http://somup.com/creX0bb1Q9

**Comment by aulneau** [comment] 2021-03-12 00:33
@timstackblock are you using the extension from this PR? https://github.com/blockstack/stacks-wallet-web/pull/1053 -> https://github.com/blockstack/stacks-wallet-web/actions/runs/644353231

**Comment by hstove** [comment] 2021-03-12 05:19
Yeah, the video looks like the previous version. In the fixed version, the "Done" button has a spinner while the account is created.

**Closed as completed** 2021-03-14 13:12 UTC
Labels: bug, bug-p1
