### ISSUE TITLE
Improve Secret Key screen

### ISSUE THREAD

**Issue by jasperjansz** [leather-io/extension#1475] opened 2021-07-22 12:42 UTC
https://www.figma.com/file/VupGh90FJtT0dcBj2Sh7bb/📏Spec?node-id=80%3A3287

- [ ] edit copy
- [ ] add tips (using feather icons)
- [ ] add illustration
- [ ] add "back it up later" option
- [ ] change layout

![image](https://user-images.githubusercontent.com/28991/136795378-99443976-c09f-4696-af8c-7794f42981b2.png)

**Comment by fbwoolf** [comment] 2022-01-29 15:36
This is a duplicate of: https://github.com/hirosystems/stacks-wallet-web/issues/2152 so going to close it.

**Closed as completed** 2022-01-29 15:36 UTC
Labels: area:onboarding
