### ISSUE TITLE
Close popover menu when clicking any of the links inside

### ISSUE THREAD

**Issue by jasperjansz** [leather-io/extension#987] opened 2021-02-18 15:10 UTC
When I click any link in the popover menu, e.g. "View secret key", it should close when it navigates to the page. Currently, it stays open.

![image](https://user-images.githubusercontent.com/25477905/108376972-d6d9d300-7203-11eb-8c07-2d7116f4b5ca.png)

**Comment by hstove** [comment] 2021-03-11 01:42
I'm not able to reproduce currently - moving to QA

**Closed as completed** 2021-03-12 17:11 UTC
